### PR TITLE
use `getImageData()` so that hash is always stable

### LINKED ISSUE #1: Use `getImageData` instead of `toDataURL` to compare snapshots
It looks like the result of `Canvas#toDataURL` depends on the platform. Tests that pass on my Mac, fail on TravisCI - see https://github.com/Automattic/node-canvas/issues/853. Maybe it would be better to use something that returns raw image data, like `Canvas#getImageData`, rather than a compressed image?

### LINKED ISSUE #3: Hashing doesn't work
According to the documentation the snapshot should contain a hash, but when I try the example this is my result:
```
<canvas
  data-snapshot-image="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAA6e...[FULL_BASE_64]"
  height="200"
  width="200"
/>
```

My test code:
```
import canvasSerializer from 'jest-canvas-snapshot-serializer';
expect.addSnapshotSerializer(canvasSerializer);

it('works with canvas', () => {
    const canvas = createCanvas('#000', '#F00'); // function from your example.
    expect(canvas).toMatchSnapshot();
  });
```

Am I missing something?

### PR DESCRIPTION
**Pull request by tjenkinson**
Closes #1 and also fixes #3. Not exactly sure how it fixed that, but it does :)

Would need to be a breaking change given it will definitely generate new hashes to previous versions.

### CODE REVIEW

**Comment by IPWright83** [comment]
@tjenkinson I'm wondering the best way to get this merged - @bseber are you still active on this rep at all?

**Comment by bseber** [comment]
hey @tjenkinson, hey @IPWright83 there are actually people out there using this library 🎉 That's awesome, really. Thanks :-)

Unfortunately I'm not active on this project anymore. I even lost track of why I've created it at the first place.

Nevertheless I'm going to merge this, bump some more dependencies and publish a new version.

**Comment by bseber** [comment]
Unfortunately it's still broken: https://github.com/synyx/jest-canvas-snapshot-serializer/runs/4143368578?check_suite_focus=true

And I don't have time to fix this currently.

Maybe [Playwright](https://playwright.dev) and `jest-image-snapshot` is an alternative?

* https://playwright.dev/docs/screenshots#element-screenshot

```
const screenshot = await page.screenshot();
expect(screenshot).toMatchImageSnapshot();
```

**Comment by IPWright83** [comment]
@bseber I'm hoping to use this library fairly extensively soon (if I can). It's certainly working locally though not tested on CI yet.

I might put some PR's together if you're OK to review them? Unless you fancy having another contributor/publisher?

**Pull request merged**
